### ISSUE TITLE
Manual install

### ISSUE THREAD

**Issue by zipgenius** [noweh/twitter-api-v2-php#10]
Hello.
I can't use composer: can twitter-api-v2-php be installed manually?

**Comment by noweh** [comment]
Hello!

This library has dependencies with guzzlehttp/guzzle and guzzlehttp/oauth-subscriber.
So I suppose that you need to build the project in your own development environment and upload the artifact (i.e. the full folder with all vendors, composer autoload, etc.) to your machine that doesn't have composer.

Regards
