### ISSUE TITLE
get access_token

### ISSUE THREAD

**Issue by 104979058** [noweh/twitter-api-v2-php#14]
Is there a ready way to get both? Need to apply: client_credentials
'access_token' => 'ACCESS_TOKEN',
 'access_token_secret' => 'ACCESS_TOKEN_SECRET'
 
thx

**Comment by noweh** [comment]
I don't understand your point.
Yes it's possible to get both.

**Comment by 104979058** [comment]
> access_token

There is no access_token in the account, every time you need to get the access_token from https://api.twitter.com/oauth2/token, is there a way to encapsulate it?
