### ISSUE TITLE
performRequest() must be of the type array

### ISSUE THREAD

**Issue by romain64** [noweh/twitter-api-v2-php#28]
Hello, j'utilise la fonction suivante pour envoyer un tweet:
`$client->tweet()->performRequest('POST', ['text' => 'Hello world'])`
qui me renvoit l'erreur
`Uncaught TypeError: Argument 1 passed to Noweh\TwitterApi\AbstractController::performRequest() must be of the type array, string given`
En regardant AbstractController.php la fonction attend bien un Array mais le readme précise qu'il faut un String pour la methode et un Array pour le contenu du tweet. Quelle est la manière correcte d'utiliser cette fonction?

**Comment by noweh** [comment]
Bonjour, le fichier readme était effectivement pas à jour, et le développement était encore en cours.
Une nouveau tag (3.0.0) est désormais dispo avec la doc à jour.

La version correcte sur ce tag est :
$client->tweet()->create()->performRequest([ 'text' => 'Hello world']);
