### ISSUE TITLE
Post text + image

### ISSUE THREAD

**Issue by sktechnology** [noweh/twitter-api-v2-php#3]
Hi sir, is it possible to post text + image.

thx you !

**Comment by noweh** [comment]
Hi!
This does not seems possible on the Twitter API v2 yet. The feature to tweet is fairly new, hopefully they will come up with it soon!

**Comment by sktechnology** [comment]
Thx you the post function with text work very well... I have some difficulty to use the tweetSearch function do you have sample exemple if i want to extract all tweet form one specific user thx you !

**Comment by sktechnology** [comment]
Vous venez de France, je suis français aussi ( du Québec ), la function post functionne parfaitement mais pour extraire tous les tweet d'un utilisateur en particulier avez-vous un exemple merci d'avance.

**Comment by noweh** [comment]
Bonjour, dans le fichier test/TwitterTest.php il y a un test unitaire (méthode `testSearchUsers()`) qui extrait les Tweets d'un utilisateur donné (twitterdev dans ce cas). Vous pouvez vous baser sur ce dernier.

Par défaut, Tweeter ne retourne que 10 résultats. il est possible d'augmenter cette quantité en ajoutant `->addMaxResults(XXX)` avant le `->performRequest()`.

**Comment by sktechnology** [comment]
require_once 'twitterApi/vendor/autoload.php';

use Noweh\TwitterApi\Client;
use Noweh\TwitterApi\Enum\Modes;

$settings = [
'account_id' => *,
    'consumer_key' => '*',
    'consumer_secret' => '*',
    'bearer_token' => '*',
    'access_token' => '*',
    'access_token_secret' => '*'
]; 
$client = new Client($settings);


$return = $client->userSearch()
            ->findByIdOrUsername('leuser', Modes::username)
            ->performRequest();


    
var_dump($return);

Fatal error: Uncaught Error: Class 'Noweh\TwitterApi\Enum\Modes' not found

**Comment by sktechnology** [comment]
J'ai ajouter le dossier Enum ainsi que le fichier Modes.php et Operators.php j'ai maintenant cette erreur Parse error: syntax error, unexpected 'Modes' (T_STRING)

**Comment by sktechnology** [comment]
Pourtant j'avais bien fait composer require noweh/twitter-api-v2-php

**Comment by noweh** [comment]
Les "enums" ont été ajoutés à partir de la version 2.0 du bundle. La version 2.0 est compatible php >= 8.1 (version de PHP qui a ajouté la gestion des enums).

Etant sur PHP7.4, vous utilisez donc (probablement) la version 1.4.X.
Dans cette version vous devez faire l'appel suivant : 
`
$this->assertIsObject(
    $this->twitterClient->userSearch()
    ->findByIdOrUsername('twitterdev', Client::MODES['USERNAME'])
    ->performRequest()
);
`

**Comment by sktechnology** [comment]
Avec la function $return =  $client->userSearch()
    ->findByIdOrUsername('leusername', Client::MODES['USERNAME'])
    ->performRequest();

var_dump($return);

J'ai un return array avec le id, name, username mais pas de tweet à l'intérieur. merci pour ton aide ca avance

**Comment by noweh** [comment]
Hum, Je viens de me rendre compte que la méthode dont je vous ai parlé était une recherche d'utilisateurs. Pas de Tweets...
L'appel qui vous interesse est en fait ce dernier : 

    $this->twitterClient->tweetSearch()
    ->addFilterOnUsernamesFrom($usernames)
    ->performRequest()

Vous pouvez y ajouter `->onlyWithMedias();` ou `->showMetrics()` si necessaire

**Comment by sktechnology** [comment]
$return =  $client->tweetSearch()
->addFilterOnUsernamesFrom("username")
->performRequest();

var_dump($return);

Fatal error: Uncaught TypeError: Argument 1 passed to Noweh\TwitterApi\TweetSearch::addFilterOnUsernamesFrom() must be of the type array, string given, called in

**Comment by noweh** [comment]
Il faut le passer en tableau effectivement. Il est possible de faire une recherche sur un ou plusieurs usernames.

**Comment by sktechnology** [comment]
Tout fonctionne :) vous êtes génial, un gros merci pour votre travail et votre aide.
