### ISSUE TITLE
Client error: 403 Forbidden

### ISSUE THREAD

**Issue by ersanyakit** [noweh/twitter-api-v2-php#38]
Client error: `GET https://api.twitter.com/2/tweets/1671954581469757455/quote_tweets` resulted in a `403 Forbidden` response: {"client_id":"27400769","detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and to (truncated...)

`
        $settings = array(
                                "account_id"=>"1056637717700927489",
                                "access_token" => env("TWITTER_ACCESS_TOKEN"),
                                'access_token_secret'=> env("TWITTER_ACCESS_TOKEN_SECRET"),
                                'consumer_key'=>env("TWITTER_CONSUMER_KEY"),
                                'consumer_secret'=>env("TWITTER_CONSUMER_SECRET"),
                                'bearer_token'=>env("TWITTER_BEARER_TOKEN"));
         $client = new Client($settings);

        $tweetId = "1671954581469757455";
        $return = $client->tweetQuotes()->getQuoteTweets($tweetId)->performRequest();

`

**Comment by gabriel-messier** [comment]
If you are using a free developer account, you are only allowed 3 endpoints (POST /2/tweets, DELETE /2/tweets/:id and GET /2/users/me) with Twitter API v2. The worst part is that these endpoints are also really limited in how many times you can call them daily...
