### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by marcosegato** [noweh/twitter-api-v2-php#44]
Hi, I was testing the recent feature to upload media files (thanks for it), but it always ends up in an error:
```
[GuzzleHttp\Exception\ClientException: Client error: `POST https://api.twitter.com/2/tweets` resulted in a `400 Bad Request` response:
{"errors":[{"parameters":{"$.media.media_ids[0]":["1690269940228489216"]},"message":"$.media.media_ids[0]: integer found (truncated...)
```
I exactly replicated the code provided in the readme documentation file: the upload part is working fine (I get back the media id) but the posting brakes. Can you please support?
Thanks!
Note: using the free plan.

**Comment by noweh** [comment]
Thanks for your feedback.

I will make a new tag reporting the full error information (without "truncated" part).
**The complete error is :** 
`{"errors":[{"parameters":{"$.media.media_ids[0]":["1690290965297180672"]},"message":"$.media.media_ids[0]: integer found, string expected"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"}`

**And here is the fix :** 
```php
$client->tweet()->create()
    ->performRequest([
    'text' => 'Test Tweet... ', 
        'media' => [
            'media_ids' => [
                (string)$media_info["media_id"]
            ]
        ]
    ]
);
```

I update the readme file.
