### ISSUE TITLE
Nouvelle requête - repondre à un tweet.

### ISSUE THREAD

**Issue by sktechnology** [noweh/twitter-api-v2-php#5]
Bonjour,

J'espère que vous allez bien ...

J'aimerais savoir si on peut répondre à un tweet existant avec cette api.

Cordialement

**Comment by noweh** [comment]
Bonjour, la fonctionnalité de "répondre" directement à un Tweet n'est pas encore implémentée par l'API v2 Twitter.

Cependant, c'est possible sous une autre forme en deux temps : il est possible de rechercher un Tweet précis, puis de créer un nouveau Tweet auto dans lequel on taguerait l'expéditeur du précédent.
