### ISSUE TITLE
Improvement Request: Replace query string parameters concatenation with something like http_build_query for better extendability.

### ISSUE THREAD

**Issue by saqibsarwar** [noweh/twitter-api-v2-php#8]
Hi,

I would like to thank you for developing this library. 

I am planning to extend it to add some additional features. While exploring existing code a suggestion came to my mind that current way of constructing query string using string concatenation should be replaced with something like http_build_query so that we can easily replace a parameter value in children class if needed.

Thanks

**Comment by noweh** [comment]
Hi,
Thanks for your words. That could actually be a great idea !
